import type { Metadata } from "next";
import RecoilRootWrapper from "./RecoilWrapper";
import "@/styles/globals.css";
import ClientWrapper from "./ClientWrapper";

export const metadata: Metadata = {
  title: "Flow Studio",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon/logo.png',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ClientWrapper>
          <RecoilRootWrapper>{children}</RecoilRootWrapper>
        </ClientWrapper>
      </body>
    </html>
  );
}
