import type { Metadata } from "next";
import "@/styles/globals.css";
import Header from "@/components/common/Header";

export const metadata: Metadata = {
  title: "Flow Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header/>   
        <main className="mt-[60px]">
          {children}
        </main>   
      </body>
    </html>
  );
}
